### PR TITLE
SQL query string should be escaped

### PR DESCRIPTION
**Pull request by mark86092**
Just because I try to send ... `I'm`

### CODE REVIEW

**Comment by qcl** [comment]
I will fix the CI process before merge it, thanks your PR, LGTM.

**Comment by qcl** [comment]
I'd modify CI settings, I will close then re-open this PR, thanks.

**Comment by qcl** [comment]
Re-open it then try new CI setting.

**Comment by qcl** [comment]
:shipit:

**Comment by mark86092** [comment]
Please do it at will, no problem :)

**Pull request merged**
