### PR TITLE
add Python implementation

### PR DESCRIPTION
**Pull request by shaform**
I tried my best to implement the following behavior:

```
from QCL import *            | qcl@QCLS:~$ python qcl.py             這Code   
if __name__ == '__main__':   | Tracebook (most recent call last):   有Bug...  
  qcl = QCL()                |   File "qcl.py", line 5, in <module>        ◤ 
  girl = qcl.getGirlFriend() |     print girl.name                〒    〒
  print girl.name            | AttributeError: 'NoneType' object  ▼ ▼ ▼ ▼ 
   ψ hahaohnoc3 修改:qcl     | has no attribute 'name'           \▲ ▲ ▲ ▲ / =
```

### CODE REVIEW

**Comment by qcl** [comment]
I do not hope that I have NO girlfriend, but now I am not sure if I have or not, so I will deal with this PR after I confirm it. If the result is I still having no girlfriend, I will merge it, thanks.

**Comment by shaform** [comment]
I could sense something is happening >///<? Good luck!

**Comment by qcl** [comment]
I think it's time to merge it, but it may take some time for me to think how to design libGF seriously.

**Comment by qcl** [comment]
Because I plan to discuss the structure of libGF, I close this PR, thanks for sending this PR :)

**Pull request closed without merging**
